### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by psalmn** [rianoc/qParquet#1]
Hi - thanks for this, looks very useful.

Would you be able to clarify the terms of use, and add a suitable license for this module please?

Thanks!

**Comment by rianoc** [comment]
I have added an [MIT licence](https://github.com/rianoc/qParquet/blob/master/LICENSE.md) which is open so you can use as you wish.

**Comment by psalmn** [comment]
Thanks a lot Rian, much appreciated!
